version: '3.8'

services:
  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - "8080:4000"
    depends_on:
      - psql
    volumes:
      - ./auth:/go/src/app
    networks:
      - app-network
    environment:
      PORT: ${PORT:-4000}
      APP_ENV: ${APP_ENV}
      DB_HOST: psql
      DB_PORT: ${DB_PORT:-5432}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_SCHEMA: ${DB_SCHEMA}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4000/health" ]
      interval: 10s
      timeout: 10s
      retries: 3

  psql:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - psql_volume:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  psql_volume:


networks:
  app-network:
