services:
  auth:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:4000"
    depends_on:
      - psql
    volumes:
      - ./:/go/src/app
    networks:
      - app-network
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:
    driver: bridge
